### ISSUE TITLE
Streaming freezes after a few seconds

### ISSUE THREAD

**Issue by ammen99** [benzea/gnome-screencast#20]
I have tried with both the Screencast portal and the X11 interface, it streams successfully for a few seconds (albeit it lags a lot, whereas streaming from my phone is pretty smooth). After like 20-30 seconds my TV simply gets stuck on one frame (at least that's what I see). There are no errors/warnings in the output with the Screencast portal, except that audio can't be recorded fast enough. Tell me if I can provide any more information or how I can debug it, I find the project super cool :)

**Comment by benzea** [comment]
Yes, I know that it lags a lot. Unfortunately, the OpenH264 codec is quite slow to encode sometimes and `gnome-screencast` intentionally inserts a lot of lag to prevent audio from stuttering (the message you are seeing).

It obviously shouldn't get stuck completely, so that is kind of odd.

For a start, could you run with `G_MESSAGES_DEBUG=all gnome-screencast` to see if any interesting messages are printed?

**Comment by benzea** [comment]
Ah, also, I would be curious if you do get an audio at that point.

**Comment by ammen99** [comment]
Here is the log, with all debug messages, I didn't see anything wrong: http://ix.io/1Fim
I also didn't get any audio at any point I think. Will try again.

**Comment by benzea** [comment]
Hrm, I am kind of suspecting that the hickup in the encoder is causing all/most frames to be discarded suddenly.
```
** (gnome-screencast:8668): DEBUG: 15:09:48.100: QOS: proportion: 14,829, processed: 862, dropped: 5
** (gnome-screencast:8668): DEBUG: 15:09:50.332: QOS: proportion: 57,487, processed: 865, dropped: 80
```
is suspicious, as only  3 frames were processed within two seconds.


There is also one bug at least, but it is likely unrelated:
```
(gnome-screencast:8668): GLib-GObject-WARNING **: 15:09:16.673: g_object_set_is_valid_property: object class 'GstVaapiEncodeH264' has no property named ''
```

This means that there is a confusion as that code which configures the pipeline is trying to set up the OpenH264 encoder (but a vaapi based one was created earlier).

**Comment by benzea** [comment]
Fixed the warning. It caused us to not setup the VAAPI encoder correctly). So that might actually improve the situation, but I don't expect by much.

**Comment by ammen99** [comment]
Thanks for the fast response, unfortunately I can't test again atm, but I will post an update as soon as I can.

Unrelated, but is a significant delay (like >1 second) between what happens on the screen and on the TV normal? It makes using this unusable except as for playing videos and such.

**Comment by benzea** [comment]
Yes, the delay is expected currently. As I said, video encoding is sometimes rather slow and the solution for now is to delay everything so that audio/video can remain in sync when such a delay happens.

The delay should be less than a second though.

**Comment by ammen99** [comment]
Hi again, I pulled the latest changes, but now it won't even connect. Connecting from my phone works though, so it is definitely a problem with this tool. No errors or warnings, it is just stuck in some WAIT_SOCKET state, until it times out.

EDIT: I tried rolling back to the commit I was using before, and it is still the same result (no connection), so probably we should try to debug this first.

**Comment by benzea** [comment]
Ah. Maybe just a reboot and SELinux is enforcing again or something like that? Though, then it should fail earlier, I think.

**Comment by ammen99** [comment]
Just tested, and I can somehow connect again, although I need to try 2-3 times before it succeeds. SELinux is not enforcing, I have checked.

**Comment by benzea** [comment]
Hmm, could well be that there are some issues with connecting; probably something to solve somewhere in the stack and it might be hard to pinpoint what exactly is going wrong.

Anyway, I assume the issue that things stop after a while is still there?

**Comment by ammen99** [comment]
Yes, this one is happening each time I manage to connect to my TV.

**Comment by ammen99** [comment]
Also if that can help, the same happens with the X11 fallback (tried on i3/Xorg), but it works fine locally (i.e with `SCREENCAST_DUMMY=1` + playing in `vlc`)

**Comment by benzea** [comment]
Oh, that is an interesting data point. Because that means we are probably still streaming correctly (maybe with a short hickup having happened at one point). What might also be interesting is that 25s is the time where we do the keep-alive signal on the RTSP channel. It doesn't seem likely, but I cannot rule out that the keep-alive isn't working properly for you (which would result in a disconnect after 30s).

**Comment by benzea** [comment]
This is a long shot, but maybe try the following change:
```
diff --git a/src/wfd/wfd-client.c b/src/wfd/wfd-client.c
index 1b29565..89f8f5b 100644
--- a/src/wfd/wfd-client.c
+++ b/src/wfd/wfd-client.c
@@ -356,7 +356,7 @@ wfd_client_timeout_session_filter_func (GstRTSPClient  *client,
 
   g_debug ("WfdClient: Doing keep-alive");
 
-  gst_rtsp_message_init_request (&msg, GST_RTSP_GET_PARAMETER, "rtsp://localhost/wfd1.0/streamid=0");
+  gst_rtsp_message_init_request (&msg, GST_RTSP_GET_PARAMETER, "rtsp://localhost/wfd1.0");
 
   gst_rtsp_client_send_message (client, sess, &msg);
 
```

I just checked the specification, and it looks like that is more correct.

**Comment by ammen99** [comment]
Still hangs, but indeed it seems that it hangs a bit after the "Doing keep-alive" message.

**Comment by benzea** [comment]
Alright, lets grab a dump of the network traffic and see if we can see something then. The following should do the trick (even if it is a bit ugly):

```
interface=""; while [ -z "$interface" ]; do interface=$( ls /sys/class/net/ | grep -- p2p- ); sleep 0.1; done; echo $interface; tcpdump -i "$interface" -w /tmp/p2p-connection-dump.pcap
```

**Comment by ammen99** [comment]
Not sure where to upload, so Dropbox: https://www.dropbox.com/s/st0eba4losjgysp/p2p-connection-dump.pcap?dl=0
EDIT: What is in this pcap: I started gnome-screencast, started the recording tool, then selected sink, after it connected I waited for it to get stuck, then cancelled streaming.

**Comment by benzea** [comment]
Thanks. I was really only interested in the .pcap part (the entire video stream is in the pcap file).

I don't see anything obvious and to be honest, I am kind of out of ideas for now. As a data point, could you provide some information about the sink (i.e. TV in question)?

**Comment by ammen99** [comment]
The TV is Sony KD 55XF7005. Do you know some link where I can read more about Miracast and related technologies, I might have some time tomorrow to look into it myself, although I don't know much.

**Comment by benzea** [comment]
Could you email me? I can send you some info, I think.

**Comment by maciejmrozinski** [comment]
Hi. Didn't want to create new issue, because mine looks very similar to what @ammen99 described. Video is shown, no audio on projector speaker (Epson EH-TW5650). Video is delayed (I read that this is expected), video shutters all the time and then freezes after 20-30s. Below I attach log file with option G_MESSAGES_DEBUG=all: 
[gnome-screencast.log](https://github.com/benzea/gnome-screencast/files/3113896/gnome-screencast.log)
Any help appreciated :)

**Comment by benzea** [comment]
Hmm, I wonder where that is coming from; now that could be an issue. That is X11, so maybe that explains why I never saw the pipeline issues.
```
Warning from inter video sink: Pipeline construction is invalid, please add queues.
Warning from media-pipeline: GStreamer error: clock problem.
```

**Comment by benzea** [comment]
For audio you need to manually switch the audio sink to "GNOME-Screencast".

**Comment by maciejmrozinski** [comment]
Just forgot to mention operating system: Ubuntu 19.04. Thanks for audio tip, it worked until video freezes.

**Comment by ammen99** [comment]
I sadly no longer have access to the TV I was testing with, but I was also getting the pipeline issues when running under X11 (don't remember seeing them while in Gnome though)

**Comment by pitlochry** [comment]
I do not want to create new issue, because mine looks identical to what @ammen99 and @maciejmrozinski describe.

- Fresh fedora 30 system with latest screencast version from git, so everything should work as expected.

- Tested on following sinks: 
LG PF50KA
Epson EB-2247U
On both sinks streaming freezes after approx 30 seconds. Tried it with fedora on several laptops (via usb stick), all on which windows miracast is working flawlessly.

- ND_DUMMY=1 (resp. SCREENCAST_DUMMY=1) works as expected and does not freeze.
setenforce 0 does not help

- G_DEBUG_MESSAGES=all gnome-network-displays 
no errors
[@maciejmrozinski I had similar errors on arch due to outdated version 1.14 of gstreamer/gst with falling back to x11, 1.16 did the trick]

- journalctl --since "2 min ago"
see [journalctl.txt](https://github.com/benzea/gnome-screencast/files/3195064/journalctl.txt)
Annotations:
ca. 10:27:00 starting gnome-network-displays
ca. 10:27:30 connection succeeded
ca. 10:28:00 freezes

Is there anything we could do to debug this issue?

**Comment by benzea** [comment]
I still haven't been able to reproduce it :-/

So, what you can do is running with `GST_DEBUG=*:5` (or even higher debug levels, 6 is "log, 7 is "trace"); maybe we can see something there.

**Comment by pitlochry** [comment]
- [This](https://www.dropbox.com/s/d92j0posiiptgsz/a5?dl=0) is the output of GST_DEBUG=\*:5 gnome-network-displays. It got quite large (500MB), so I uploaded it on dropbox. The last line before the stream froze was 0:01:07.411427582.
I could also upload files with GST_DEBUG=\*:6 and GST_DEBUG=\*:7.

- The moment the stream freezes, the network traffic declines to 0, whereas ram and cpu usage stay constantly high (450MB ram, 25% CPU).

- The last thing I can think of trying is to test your copr version of screencast and network manager (I will do it on Monday/Tuesday). Perhaps I built it the wrong way. On a fresh fedora 30 system I did:
sudo dnf config-manager --set-enabled fedora-cisco-openh264
sudo dnf install gstreamer1-plugins-base-devel gstreamer1-rtsp-server-devel gtk3-devel libnma-devel pulseaudio-libs-devel gstreamer1-plugin-openh264 
git clone https://github.com/benzea/gnome-screencast
cd gnome-screencast
meson . build --prefix /usr 
ninja -C build
sudo DESTDIR="$pkgdir" ninja -C build install

- Do you have any further ideas to solve this issue? Thanks

**Comment by benzea** [comment]
* The last thing I can think of trying is to test your copr version of screencast and network manager

Please don't, that would be a waste of time :)

Just form your description, CPU usage still high but no traffic sounds like all Video frames start getting discarded somewhere. I really have some hope that the debug output (even if huge) will give some indication as to why this is happening.

**Comment by pitlochry** [comment]
Yesterday I removed the git version build and installed your copr version of gnome-screencast. And streaming didn't freeze... So there has to be a mistake in my proceedings to build the git-version: Either a mistake in the build-commands itself, or a missing dependency which I have not installed (and which is not checked when running meson, as meson says YES to every checked dependency). [Here](https://github.com/benzea/gnome-screencast/issues/20#issuecomment-495904209) is how I built it.

After changing the audio output in gnome-settings to "gnome-screencast"/"Network-Displays", the stream freezes after about 30 s. Obviously since I had not installed faac. So freezing after some time seems to imply that dependencies are missing... (?) strange

So next step is to test the git version with more dependencies. First thing to try is gstreamer1-plugins-ugly-free-devel. Alas, next time I can access the projector is next Tuesday.

**Comment by benzea** [comment]
Well, there are audio encoders that can be used currently, faac being one of them. If you don't have one of these then the pulseaudio sink is created, but will never be used.

That could mean though that we only run into the issue with the faac audio encoder though.

**Comment by benzea** [comment]
So, what appears to happen is that *all* frames are dropped by the videoscale element. I am kind of surprised by this, as I am not sure why we would be dropping them there. Maybe I need to disable handling of `qos` messages in all elements except the encoder.

**Comment by benzea** [comment]
@pitlochry, could you try the following patch:

[0001-media-factory-Disable-QOS-handling-in-video-pre-proc.patch.txt](https://github.com/benzea/gnome-screencast/files/3233104/0001-media-factory-Disable-QOS-handling-in-video-pre-proc.patch.txt)

**Comment by pitlochry** [comment]
Yes, thanks, i can try the patch, as soon as I have access to the projector (on Tuesday, 2019-06-04)

**Comment by pitlochry** [comment]
Sorry for late response. 

1. I have to correct one of my last statements: Your copr version shows the very same behaviour than the git compiled versions: In general streaming freezes, rarely it does not (see 3.)
2. I applied your patch and it didn't change the behaviour.
3. I ran many tests with all three video encoders. In approx 5 of every 100 tests streaming does *not* freeze. Crazy... The output of G_MESSAGES_DEBUG=all gnome-network-displays is different if it freezes or not:
If it does not freeze there are (for x264 and openh264) plenty of "Forcing a keyframe!" messages (approx every second), if it does freeze, there is only one "Forcing a keyframe!" message. For vaapih264 there is the message "Cannot force key frame as the pipeline doesn't support it!" instead of "Forcing a keyframe!". Here are the output files: [vaapih264_works.txt](https://github.com/benzea/gnome-screencast/files/3267584/vaapih264_works.txt) [x264_freezes.txt](https://github.com/benzea/gnome-screencast/files/3267585/x264_freezes.txt) [x264_works.txt](https://github.com/benzea/gnome-screencast/files/3267586/x264_works.txt)

I hope this is helpful.

**Comment by benzea** [comment]
Just a quick heads up. I am quite busy with other things currently but intend to look into this again.

The "forcing a keyframe" means that the device is requesting a keyframe. So I guess we are dealing with packet loss for some reason. Quite likely, the reason why I never saw those issues is that I had my test device very close to the laptop, resulting in a really stable wifi connection.

This is probably related to the QOS handling in some way. Either because we are not changing the bitrate currently (I am not even sure how that would work for a UDP stream) or because my QOS handling that exist to ensure realtime encoding is broken in some way.

**Comment by benzea** [comment]
So, quite possibly, all that is needed is two kinds of QOS handling. One for realtime (which I have) and another one to properly modify the bitrate dynamically. For the second it might be an advantage to try to use a TCP stream instead.

**Comment by benzea** [comment]
So, quite possibly, all that is needed is two kinds of QOS handling. One for realtime (which I have) and another one to properly modify the bitrate dynamically. For the second it might be an advantage to try to use a TCP stream instead.

**Comment by pitlochry** [comment]
Thanks. Since I do not know how to "use a TCP stream instead" I just want to thank you for your patience and time you spend for free software.
In the meantime I bought a 10m hdmi cable to use instead of wifi-direct, but I will test from time to time, if the bug vanishes. If you need any other output or have any other ideas, I'd be glad to help.

**Comment by ammen99** [comment]
@benzea I at last have access to the TV I was testing with, and will probably have access in the next few weeks. What is the current status?

**Comment by benzea** [comment]
Sorry, I was busy with other things and did not get around to do any further debugging. Which is complicated by the fact that I am still not sure where to start looking to fix this issue.

**Comment by ammen99** [comment]
@benzea Okay. I will be at the TV around the beginning of October, maybe I'll poke around and check if I can find something suspicious.

**Comment by benzea** [comment]
I pushed a fix that may help in this case and with other streaming issues.

I'll probably experiment a bit more in the next few days.

**Comment by ammen99** [comment]
@benzea Sadly I tried the latest gnome-network-displays and it doesn't work still... However it now prints one more message:

```
** (gnome-network-displays:14573): DEBUG: 22:31:01.348: WfdClient: Doing keep-alive
```

Up to this point and shortly afterwards everything works. Then suddenly:

```
** (gnome-network-displays:14573): DEBUG: 22:31:12.400: WfdMedia: Finalize
```

At this point the image on the TV gets stuck.

**Comment by benzea** [comment]
So, this looks like the same issue as #62. For some reason we seem to drop the connection (I am guessing on a low level).

@ammen99, as a reference point, what wifi adapter do you have?

I am suspecting this is a bug on the NM/wpa_supplicant side (more likely NM), but I really still have no idea unfortunately and I need to think about how to pinpoint it.

**Comment by ammen99** [comment]
@benzea I have tested with 2 different laptops, one is Lenovo Yoga 510 the other is Thinkpad X380

**Comment by benzea** [comment]
@ammen99, hey, I had an idea what is happening. If you have access to a device and the time, could you grab a log from NetworkManager as described in https://github.com/benzea/gnome-network-displays/issues/62#issuecomment-536646740?

**Comment by ammen99** [comment]
@benzea I have the logs, can i send them via email?

**Comment by benzea** [comment]
@ammen99 of course! Just mail them to benjamin@sipsolutions.net.

**Comment by benzea** [comment]
Oh wow, I just looked at the pcap file again, and I think I know what might be going on:

```
GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
CSeq: 5
Server: GStreamer RTSP server
Session: OewAUoCIAdC0BBvU
Date: Mon, 08 Apr 2019 11:39:05 GMT

RTSP/1.0 200 OK
CSeq: 5
```

The device is not including the `Session` header in the response there. And I digged through the gst-server code yesterday, and it may be that this means the response is either ignored completely or does not cause in the keep-alive to happen.

**Comment by benzea** [comment]
@ammen99, I pushed a fix (i.e. 6afa893c7f58ad3a511791ae1f55bca5584c3196), could you test whether this fixes the problem for you?

I am pretty damn sure it will, but I can't verify it unfortunately.

**Comment by pitlochry** [comment]
@benzea Today was the last day at work where I could test the fix. Mid of January I might get back to work and test.

**Comment by ammen99** [comment]
@benzea Very nice! It works now.

An unrelated question: is there anything I can do to improve latency? I suppose the connection is good enough (both TV and laptop are in the same room, so no signal loss).

**Comment by ammen99** [comment]
Nvm, I just patched gnome-network-displays to set zero latency to the pipeline, seems to work fine (of course, there is still a much smaller delay, but I guess this is unavoidable.). Thanks once again!

**Comment by benzea** [comment]
I think one might be able to lower the latency. The "fun" thing is that some/most encoders introduce quite a lot of latency occasionally. At that point the pipeline will automatically insert more latency. so it might be that the latency increases again a lot after a bit of playing.
