### ISSUE TITLE
No image although it's connected

### ISSUE THREAD

**Issue by ibesora** [benzea/gnome-screencast#78]
Hi, I'm using Ubuntu 19.04 and trying to connect to an LG non-WebOS television.
Although it's connected and the television shows that, no feed is being sent. 

`nmcli` shows the following result:
```
p2p-dev-wlp2s0: connected to Wi-Fi P2P Peer 12:08:C1:89:E1:D0
        "p2p-dev-wlp2s0"
        wifi-p2p, hw, iface p2p-wlp2s0-1, mtu 1500
        inet4 192.168.16.20/24
        route4 192.168.16.0/24
        inet6 fe80::cf6c:26b9:8d54:e16c/64
        route6 fe80::/64
        route6 ff00::/8
```
so it seems we really are connected. 
The output of `gnome-network-displays` is showing these warnings:

```
** (gnome-network-displays:9091): WARNING **: 19:40:06.653: Error calling DBus method during Screencast portal initialization: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
** (gnome-network-displays:9091): WARNING **: 19:40:06.653: Error initing screencast portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
** (gnome-network-displays:9091): WARNING **: 19:40:06.653: Screencasting portal is unavailable! It is required to select the monitor to stream!
** (gnome-network-displays:9091): WARNING **: 19:40:06.653: Falling back to X11! You need to fix your setup to avoid issues (XDG Portals and/or mutter screencasting support)!
** (gnome-network-displays:9091): WARNING **: 19:40:16.681: Resolution 29 not found in table VESA, but was in suppliments 0x3FFFFFFF
** (gnome-network-displays:9091): WARNING **: 19:40:16.682: Resolution 29 not found in table VESA, but was in suppliments 0x3FFFFFFF
** (gnome-network-displays:9091): WARNING **: 19:40:16.682: WfdClient: No resolution found, falling back to standard FullHD resolution.
```
and nothing else

Am I missing something ?
Thanks!

**Comment by ibesora** [comment]
Running with `G_MESSAGES_DEBUG=all` shows this output:
```
** (gnome-network-displays:14049): DEBUG: 20:09:05.432: selected resolution 1920, 1080 @30
** (gnome-network-displays:14049): DEBUG: 20:09:05.445: WfdClient: SET_PARAMS done
** (gnome-network-displays:14049): DEBUG: 20:09:05.452: WfdClient: Initialization done!
** (gnome-network-displays:14049): DEBUG: 20:09:05.453: use x11: 1
** (gnome-network-displays:14049): DEBUG: 20:09:05.561: WfdMedia init: Got 1 streams
** (gnome-network-displays:14049): DEBUG: 20:09:08.485: QOS: proportion: 0.500, processed: 20, dropped: 1
** (gnome-network-displays:14049): DEBUG: 20:09:08.494: QOS: proportion: 0.500, processed: 20, dropped: 2
** (gnome-network-displays:14049): DEBUG: 20:09:08.502: QOS: proportion: 0.500, processed: 20, dropped: 3
** (gnome-network-displays:14049): DEBUG: 20:09:08.511: QOS: proportion: 0.500, processed: 20, dropped: 4
** (gnome-network-displays:14049): DEBUG: 20:09:08.519: QOS: proportion: 0.500, processed: 20, dropped: 5
** (gnome-network-displays:14049): DEBUG: 20:09:08.525: QOS: proportion: 0.500, processed: 20, dropped: 6
** (gnome-network-displays:14049): DEBUG: 20:09:08.530: QOS: proportion: 0.500, processed: 20, dropped: 7
** (gnome-network-displays:14049): DEBUG: 20:09:08.537: QOS: proportion: 0.500, processed: 20, dropped: 8
** (gnome-network-displays:14049): DEBUG: 20:09:08.545: QOS: proportion: 0.500, processed: 20, dropped: 9
** (gnome-network-displays:14049): DEBUG: 20:09:08.551: QOS: proportion: 0.500, processed: 20, dropped: 10
** (gnome-network-displays:14049): DEBUG: 20:09:08.558: QOS: proportion: 0.500, processed: 20, dropped: 11
** (gnome-network-displays:14049): DEBUG: 20:09:08.565: QOS: proportion: 0.500, processed: 20, dropped: 12
** (gnome-network-displays:14049): DEBUG: 20:09:08.569: QOS: proportion: 0.500, processed: 20, dropped: 13
** (gnome-network-displays:14049): DEBUG: 20:09:08.575: QOS: proportion: 0.500, processed: 20, dropped: 14
** (gnome-network-displays:14049): DEBUG: 20:09:08.582: QOS: proportion: 0.500, processed: 20, dropped: 15
** (gnome-network-displays:14049): DEBUG: 20:09:08.587: QOS: proportion: 0.500, processed: 20, dropped: 16
** (gnome-network-displays:14049): DEBUG: 20:09:08.592: QOS: proportion: 0.500, processed: 20, dropped: 17
** (gnome-network-displays:14049): DEBUG: 20:09:08.597: QOS: proportion: 0.500, processed: 20, dropped: 18
** (gnome-network-displays:14049): DEBUG: 20:09:08.602: QOS: proportion: 0.500, processed: 20, dropped: 19
** (gnome-network-displays:14049): DEBUG: 20:09:08.607: QOS: proportion: 0.500, processed: 20, dropped: 20
** (gnome-network-displays:14049): DEBUG: 20:09:08.611: QOS: proportion: 0.500, processed: 20, dropped: 21
** (gnome-network-displays:14049): DEBUG: 20:09:08.616: QOS: proportion: 0.500, processed: 20, dropped: 22
** (gnome-network-displays:14049): DEBUG: 20:09:08.619: QOS: proportion: 0.500, processed: 20, dropped: 23
** (gnome-network-displays:14049): DEBUG: 20:09:08.623: QOS: proportion: 0.500, processed: 20, dropped: 24
** (gnome-network-displays:14049): DEBUG: 20:09:08.626: QOS: proportion: 0.500, processed: 20, dropped: 25
** (gnome-network-displays:14049): DEBUG: 20:09:08.632: QOS: proportion: 0.500, processed: 20, dropped: 26
** (gnome-network-displays:14049): DEBUG: 20:09:08.640: QOS: proportion: 0.500, processed: 20, dropped: 27
** (gnome-network-displays:14049): DEBUG: 20:09:08.647: QOS: proportion: 0.500, processed: 20, dropped: 28
** (gnome-network-displays:14049): DEBUG: 20:09:08.659: QOS: proportion: 0.500, processed: 20, dropped: 29
** (gnome-network-displays:14049): DEBUG: 20:09:08.667: QOS: proportion: 0.500, processed: 20, dropped: 30
** (gnome-network-displays:14049): DEBUG: 20:09:08.671: QOS: proportion: 0.500, processed: 20, dropped: 31
** (gnome-network-displays:14049): DEBUG: 20:09:08.677: QOS: proportion: 0.500, processed: 20, dropped: 32
** (gnome-network-displays:14049): DEBUG: 20:09:08.679: QOS: proportion: 0.500, processed: 20, dropped: 33
** (gnome-network-displays:14049): DEBUG: 20:09:08.688: QOS: proportion: 0.500, processed: 20, dropped: 34
** (gnome-network-displays:14049): DEBUG: 20:09:08.691: QOS: proportion: 0.500, processed: 20, dropped: 35
** (gnome-network-displays:14049): DEBUG: 20:09:08.696: QOS: proportion: 0.500, processed: 20, dropped: 36
** (gnome-network-displays:14049): DEBUG: 20:09:08.706: QOS: proportion: 0.500, processed: 20, dropped: 37
** (gnome-network-displays:14049): DEBUG: 20:09:08.718: QOS: proportion: 0.500, processed: 20, dropped: 38
** (gnome-network-displays:14049): DEBUG: 20:09:08.721: QOS: proportion: 0.500, processed: 20, dropped: 39
** (gnome-network-displays:14049): DEBUG: 20:09:08.734: QOS: proportion: 0.500, processed: 20, dropped: 40
** (gnome-network-displays:14049): DEBUG: 20:09:08.737: QOS: proportion: 0.500, processed: 20, dropped: 41
** (gnome-network-displays:14049): DEBUG: 20:09:08.742: QOS: proportion: 0.500, processed: 20, dropped: 42
** (gnome-network-displays:14049): DEBUG: 20:09:08.746: QOS: proportion: 0.500, processed: 20, dropped: 43
** (gnome-network-displays:14049): DEBUG: 20:09:08.753: QOS: proportion: 0.500, processed: 20, dropped: 44
** (gnome-network-displays:14049): DEBUG: 20:09:08.755: QOS: proportion: 0.500, processed: 20, dropped: 45
** (gnome-network-displays:14049): DEBUG: 20:09:08.758: QOS: proportion: 0.500, processed: 20, dropped: 46
** (gnome-network-displays:14049): DEBUG: 20:09:08.761: QOS: proportion: 0.500, processed: 20, dropped: 47
** (gnome-network-displays:14049): DEBUG: 20:09:08.764: QOS: proportion: 0.500, processed: 20, dropped: 48
** (gnome-network-displays:14049): DEBUG: 20:09:08.769: QOS: proportion: 0.500, processed: 20, dropped: 49
** (gnome-network-displays:14049): DEBUG: 20:09:08.770: QOS: proportion: 0.500, processed: 20, dropped: 50
** (gnome-network-displays:14049): DEBUG: 20:09:08.771: QOS: proportion: 0.500, processed: 20, dropped: 51
** (gnome-network-displays:14049): DEBUG: 20:09:08.773: QOS: proportion: 0.500, processed: 20, dropped: 52
** (gnome-network-displays:14049): DEBUG: 20:09:08.783: An audiocodec has been selected: yes
** (gnome-network-displays:14049): DEBUG: 20:09:33.981: WfdClient: Doing keep-alive
** (gnome-network-displays:14049): DEBUG: 20:09:53.919: WFDP2PProvider: Peer removed
** (gnome-network-displays:14049): DEBUG: 20:09:53.919: MetaSink: No usable sink is left, object has become invalid.
** (gnome-network-displays:14049): DEBUG: 20:09:53.919: SinkList: Removing a sink
** (gnome-network-displays:14049): DEBUG: 20:09:58.982: WfdClient: Doing keep-alive
** (gnome-network-displays:14049): DEBUG: 20:10:23.981: WfdClient: Doing keep-alive
** (gnome-network-displays:14049): DEBUG: 20:10:48.981: WfdClient: Doing keep-alive
```
so it seems that some frames are dropped, the sink is removed and then the client is just doing keep-alives.
I don't know why the client is removed because the tv is still showing the miracast interface.

**Comment by benzea** [comment]
Uhhm, it kinda looks like the TV is never requesting us to actually start streaming …

The best thing would be a tcpdump (e.g. using wireshark) of the p2p interface that is dynamically created. A quick thing you can do though is to run with `GST_DEBUG=rtspclient:5` which should give some more information.

**Comment by benzea** [comment]
That should show something like:
```
0:00:05.654905914 2167690 0x559031a904f0 INFO              rtspclient rtsp-client.c:3527:handle_request: client 0x5590317454e0: received a request SETUP rtsp://127.0.0.1:7236/wfd1.0/streamid=0 1.0
0:00:05.654930881 2167690 0x559031a904f0 INFO              rtspclient rtsp-client.c:1021:find_media: reusing cached media 0x559031741940 for path /wfd1.0
0:00:05.654994497 2167690 0x559031a904f0 INFO              rtspclient rtsp-client.c:660:client_watch_session: watching session 0x7f89d0083df0
0:00:05.655065775 2167690 0x559031a904f0 DEBUG             rtspclient rtsp-client.c:2294:rtsp_ctrl_timeout_remove: rtsp control session removed timeout id=4.
0:00:05.655378019 2167690 0x559031a904f0 DEBUG             rtspclient rtsp-client.c:1958:parse_transport: parsing transports RTP/AVP;unicast;client_port=40386-40387
0:00:05.655394229 2167690 0x559031a904f0 INFO              rtspclient rtsp-client.c:1979:parse_transport: found valid transport RTP/AVP;unicast;client_port=40386-40387
0:00:05.656240058 2167690 0x559031a904f0 INFO              rtspclient rtsp-client.c:3527:handle_request: client 0x5590317454e0: received a request PLAY rtsp://127.0.0.1:7236/wfd1.0/ 1.0
0:00:07.838807384 2167690 0x559031a904f0 FIXME             rtspclient rtsp-client.c:1817:handle_play_request:<WfdClient@0x5590317454e0> Add support for seek style (null)
0:00:31.396559483 2167690 0x559031a904f0 INFO              rtspclient rtsp-client.c:3746:handle_response: client 0x5590317454e0: received a response
0:00:35.842488981 2167690 0x559031a904f0 INFO              rtspclient rtsp-client.c:3527:handle_request: client 0x5590317454e0: received a request GET_PARAMETER rtsp://127.0.0.1:7236/wfd1.0/ 1.0
0:00:56.396050916 2167690 0x559031a904f0 INFO              rtspclient rtsp-client.c:3746:handle_response: client 0x5590317454e0: received a response
```

**Comment by willhaines** [comment]
Hi, I've just built gnome-network-displays from master on fedora 31 and have the same problem. Running with GST_DEBUG=rtspclient:5 gives me the following:

    0:00:20.830246816 587440      0x287a4f0 INFO              rtspclient rtsp-client.c:661:client_watch_session: watching session 0x7f3f40006450
    0:00:20.830280430 587440      0x287a4f0 DEBUG             rtspclient rtsp-client.c:2298:rtsp_ctrl_timeout_remove: rtsp control session removed timeout id=4.
    ** (gnome-network-displays:587440): DEBUG: 09:58:28.763: An audiocodec has been selected: yes
    0:00:20.830561314 587440      0x287a4f0 DEBUG             rtspclient rtsp-client.c:1962:parse_transport: parsing transports RTP/AVP/UDP;unicast;client_port=19000
    0:00:20.830574800 587440      0x287a4f0 INFO              rtspclient rtsp-client.c:1983:parse_transport: found valid transport RTP/AVP/UDP;unicast;client_port=19000
    0:00:21.011773552 587440      0x287a4f0 INFO              rtspclient rtsp-client.c:3533:handle_request: client 0x25d6410: received a request PLAY rtsp://192.168.16.20/wfd1.0/streamid=0 1.0
    0:00:21.011796745 587440      0x287a4f0 ERROR             rtspclient rtsp-client.c:3699:handle_request: client 0x25d6410: session not found
    ** (gnome-network-displays:587440): DEBUG: 09:58:54.057: WfdClient: Doing keep-alive
    0:00:46.127782522 587440      0x287a4f0 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x25d6410: received a response

**Comment by benzea** [comment]
Why are clients so freaking buggy? Like seriously …

What I suppose is happening is, that the `PLAY` command should look something like:
```
PLAY rtsp://10.82.24.140/wfd1.0/streamid=0 RTSP/1.0
CSeq: 10
Session: 6B8B4567
```

But, your TV is not conform to the specification. It simply leaves out the `Session` header and therefore things just fall appart.

**Comment by benzea** [comment]
@willhaines @ibesora could one of you please test the patch from #103?

This is so nasty, that I won't push it without confirmation that it actually fixes a problem :)

**Comment by benzea** [comment]
That said, I am not sure that @willhaines is actually having the same problem. This fix is for the issue that @willhaines was seeing, which may or may not be the same thing.

**Comment by benzea** [comment]
Ping! Is anyone able to test the patch?

**Comment by willhaines** [comment]
Thanks for the reminder. I seem to get the same behavior with the patch. I'll attach a pcap too, in case that helps.

[gnome-network-displays.pcap.gz](https://github.com/benzea/gnome-network-displays/files/4484302/gnome-network-displays.pcap.gz)



    0:00:20.050559351 1050491      0x1608120 INFO              rtspclient rtsp-client.c:4157:gst_rtsp_client_set_connection: client 0x193f3f0 connected to server ip 192.168.16.20, ipv6 = 0
    0:00:20.050610327 1050491      0x1608120 INFO              rtspclient rtsp-client.c:4161:gst_rtsp_client_set_connection: added new client 0x193f3f0 ip 192.168.16.1:41526
    0:00:20.051082205 1050491      0x1608120 INFO              rtspclient rtsp-client.c:4763:gst_rtsp_client_attach: client 0x193f3f0: attaching to context 0x16476f0
    0:00:20.051243127 1050491      0x1608120 DEBUG             rtspclient rtsp-client.c:4775:gst_rtsp_client_attach: rtsp control setting up session timeout id=4.
    0:00:20.568218982 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:00:20.569078979 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3533:handle_request: client 0x193f3f0: received a request OPTIONS * 1.0
    0:00:20.617351519 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
 
    ** (gnome-network-displays:1050491): WARNING **: 18:07:40.022: Resolution 29 not found in table VESA, but was in suppliments 0x3FFFFFFF
 
 
    ** (gnome-network-displays:1050491): WARNING **: 18:07:40.022: Resolution 29 not found in table VESA, but was in suppliments 0x3FFFFFFF
 
 
    ** (gnome-network-displays:1050491): WARNING **: 18:07:40.022: WfdClient: No resolution found, falling back to standard FullHD resolution.
    0:00:20.628945346 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:00:20.634379596 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:00:20.638212423 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3533:handle_request: client 0x193f3f0: received a request SETUP rtsp://192.168.16.20/wfd1.0/streamid=0 1.0
    0:00:25.843172159 1050491      0x1921800 INFO              rtspclient rtsp-client.c:661:client_watch_session: watching session 0x7f5934006450
    0:00:25.843259999 1050491      0x1921800 DEBUG             rtspclient rtsp-client.c:2298:rtsp_ctrl_timeout_remove: rtsp control session removed timeout id=4.
    0:00:25.843661374 1050491      0x1921800 DEBUG             rtspclient rtsp-client.c:1962:parse_transport: parsing transports RTP/AVP/UDP;unicast;client_port=19000
    0:00:25.843691079 1050491      0x1921800 INFO              rtspclient rtsp-client.c:1983:parse_transport: found valid transport RTP/AVP/UDP;unicast;client_port=19000
    0:00:26.038642798 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3533:handle_request: client 0x193f3f0: received a request PLAY rtsp://192.168.16.20/wfd1.0/streamid=0 1.0
    0:00:26.038672479 1050491      0x1921800 ERROR             rtspclient rtsp-client.c:3699:handle_request: client 0x193f3f0: session not found
    0:00:51.058385841 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:01:16.058415469 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:01:41.058060629 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:02:06.057612871 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:02:31.057125532 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:02:56.057457868 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:03:21.172210600 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:03:46.057615596 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:04:11.158334745 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:04:36.134356891 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:05:01.060178328 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:05:26.098140995 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:05:51.057361244 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:06:16.057542436 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:06:41.074473596 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:07:06.058041101 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:07:31.056839493 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:07:56.057109734 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:08:21.057872159 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:08:46.060197012 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:09:11.171501300 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:09:36.058626926 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:10:01.059053814 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:10:26.057668042 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:10:51.057298702 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:11:16.057291580 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:11:41.094002330 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:12:06.098040322 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:12:31.057555075 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:12:56.062457615 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:13:21.057864312 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:13:46.056952335 1050491      0x1921800 INFO              rtspclient rtsp-client.c:3752:handle_response: client 0x193f3f0: received a response
    0:13:47.494283082 1050491      0x1608120 INFO              rtspclient rtsp-client.c:3425:client_session_removed: client 0x193f3f0: session 0x7f5934006450 removed
    0:13:47.494302415 1050491      0x1608120 INFO              rtspclient rtsp-client.c:685:client_unwatch_session: client 0x193f3f0: unwatch session 0x7f5934006450
    0:13:47.495053101 1050491      0x1608120 DEBUG             rtspclient rtsp-client.c:1270:gst_rtsp_client_close: client 0x193f3f0: closing connection
    0:13:47.495074162 1050491      0x1608120 DEBUG             rtspclient rtsp-client.c:1285:gst_rtsp_client_close: client 0x193f3f0: destroying watch
    0:13:47.495088290 1050491      0x1608120 INFO              rtspclient rtsp-client.c:4715:client_watch_notify: client 0x193f3f0: watch destroyed
    0:13:47.513133907 1050491      0x1608120 INFO              rtspclient rtsp-client.c:755:gst_rtsp_client_finalize: finalize client 0x193f3f0

**Comment by benzea** [comment]
Are you kidding me? Like seriously, look at this gem of messages. The first comes from our side (in response to `SETUP`) which defines the session ID, the second is from the TV.

```
RTSP/1.0 200 OK
CSeq: 2
Transport: RTP/AVP;unicast;client_port=19000;server_port=51968-51969;ssrc=00000001;mode="PLAY"
Server: GStreamer RTSP server
Session: ckOD0kLnAHwy5huY;timeout=30
Date: Thu, 16 Apr 2020 00:07:45 GMT

PLAY rtsp://192.168.16.20/wfd1.0/streamid=0 RTSP/1.0
CSeq: 3
Session: ckOD0kLnAHwy5hu
User-Agent: LGE
```

The TV is seriously chopping off the last character of the (random) session identifier!

EDIT: I suspect they have a static buffer of length 16 … if you then subtract one byte for the trailing `\0`, then you get 15 characters in the response only.

**Comment by benzea** [comment]
@willhaines, could you test the new patch from #109? At least that workaround is much cleaner.

**Comment by benzea** [comment]
@willhaines, just another reminder. Could you please test it :)

Though, maybe I should just merge it. It is really safe to do overall and should fix the issue.

**Comment by willhaines** [comment]
The patch in benzea/shorten-session-id works nicely with my LG projector.

**Comment by benzea** [comment]
What a problem … thanks a lot for testing!

**Comment by selurvedu** [comment]
Unfortunately, it does not fix my LG TV being unable to connect.

**Comment by benzea** [comment]
@selurvedu is what you are seeing maybe similar to #112?
